package com.belowzeroiq.ksunotify;

import android.app.*;
import android.os.Build;
import android.os.IBinder;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;

public class NotifyService extends Service {

    private static final String CHANNEL_ID = "ksu_state";
        private static final int NOTIF_ID = 1;
            private static final File STATE_FILE =
                        new File("/data/adb/ksu-notify/state.txt");

                            private String lastState = "";

                                @Override
                                    public void onCreate() {
                                            super.onCreate();

                                                    createChannel();
                                                            startForeground(NOTIF_ID, buildNotification("Waiting for state…"));

                                                                    new Thread(() -> {
                                                                                while (true) {
                                                                                                String state = readState();
                                                                                                                if (!state.equals(lastState)) {
                                                                                                                                    updateNotification(state);
                                                                                                                                                        lastState = state;
                                                                                                                                                                        }
                                                                                                                                                                                        try { Thread.sleep(3000); } catch (Exception ignored) {}
                                                                                                                                                                                                    }
                                                                                                                                                                                                            }).start();
                                                                                                                                                                                                                }

                                                                                                                                                                                                                    private String readState() {
                                                                                                                                                                                                                            try {
                                                                                                                                                                                                                                        if (STATE_FILE.exists()) {
                                                                                                                                                                                                                                                        BufferedReader br = new BufferedReader(new FileReader(STATE_FILE));
                                                                                                                                                                                                                                                                        String line = br.readLine();
                                                                                                                                                                                                                                                                                        br.close();
                                                                                                                                                                                                                                                                                                        return line != null ? line.trim() : "Unknown";
                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                            } catch (Exception ignored) {}
                                                                                                                                                                                                                                                                                                                                    return "Unknown";
                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                            private void updateNotification(String state) {
                                                                                                                                                                                                                                                                                                                                                    String text;
                                                                                                                                                                                                                                                                                                                                                            switch (state) {
                                                                                                                                                                                                                                                                                                                                                                        case "Horny":
                                                                                                                                                                                                                                                                                                                                                                                        text = "Thermal Disabled";
                                                                                                                                                                                                                                                                                                                                                                                                        break;
                                                                                                                                                                                                                                                                                                                                                                                                                    case "NotHorny":
                                                                                                                                                                                                                                                                                                                                                                                                                                    text = "Thermal Restored";
                                                                                                                                                                                                                                                                                                                                                                                                                                                    break;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                default:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                text = "State: " + state;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                NotificationManager nm =
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                (NotificationManager) getSystemService(NOTIFICATION_SERVICE);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        nm.notify(NOTIF_ID, buildNotification(text));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                private Notification buildNotification(String text) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return new Notification.Builder(this, CHANNEL_ID)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        .setContentTitle("KernelSU Thermal")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        .setContentText(text)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        .setSmallIcon(android.R.drawable.stat_notify_sync)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        .setOngoing(true)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        .build();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                private void createChannel() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (Build.VERSION.SDK_INT >= 26) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    NotificationChannel ch = new NotificationChannel(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        CHANNEL_ID,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "KernelSU Status",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                NotificationManager.IMPORTANCE_LOW
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        getSystemService(NotificationManager.class)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            .createNotificationChannel(ch);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            @Override
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                public IBinder onBind(android.content.Intent intent) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return null;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }